from typing import Any, Iterator, List, MutableSequence, Sequence, TypeVar, Union, overload

_T = TypeVar("_T", int, float, str)

class array(MutableSequence[Any]):
    """高效数值数组。"""

    def __init__(self, typecode: str, initializer: Union[Sequence[Any], bytes] = ...) -> None:
        """
        Args:
            typecode: 类型代码，如 'b'(有符号字节), 'B'(无符号字节),
                      'h'(有符号短整型), 'H'(无符号短整型),
                      'i'(有符号整型), 'I'(无符号整型),
                      'l'(有符号长整型), 'L'(无符号长整型),
                      'q'(有符号长长整型), 'Q'(无符号长长整型),
                      'f'(浮点), 'd'(双精度浮点)
            initializer: 初始化序列
        """
        ...

    def append(self, x: Any) -> None: ...
    def buffer_info(self) -> tuple: ...
    def byteswap(self) -> None: ...
    def count(self, x: Any) -> int: ...
    def extend(self, iterable: Sequence[Any]) -> None: ...
    def index(self, x: Any, start: int = ..., stop: int = ...) -> int: ...
    def insert(self, i: int, x: Any) -> None: ...
    def pop(self, i: int = -1) -> Any: ...
    def remove(self, x: Any) -> None: ...
    def reverse(self) -> None: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> List[Any]: ...
    def __add__(self, x: "array") -> "array": ...
    def __iadd__(self, x: "array") -> "array": ...
    def __mul__(self, n: int) -> "array": ...
    def __imul__(self, n: int) -> "array": ...
    def __rmul__(self, n: int) -> "array": ...
    def __getitem__(self, i: Union[int, slice]) -> Any: ...
    def __setitem__(self, i: Union[int, slice], x: Any) -> None: ...
    def __delitem__(self, i: Union[int, slice]) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __contains__(self, x: Any) -> bool: ...
    def __reversed__(self) -> Iterator[Any]: ...
